env:
  browser: true
  es6: true
extends: standard
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-irregular-whitespace:
    - 2
  semi:
    - error
    - never
  quotes:
    - error
    - single
  jsx-quotes:
    - error
    - prefer-single
  indent:
    - error
    - 2
  react/jsx-uses-vars:
    - 2

